project:
  name: my-cfn-project
  regions:
  - us-west-2
  - eu-north-1
tests:
  default:
    template: ./templates/my-template.yaml
    
    parameters:
      AvailabilityZones: "$[taskcat_getaz_2]"
      EmailAddress: email@yourdomain.com
      KeyPairName: YOUR-KEYPAIR-HERE
      WebserverCIDR: "0.0.0.0/0"
      QSS3KeyPrefix: "qs-workshop/"
      QSS3BucketRegion: "$[taskcat_current_region]"
      QSS3BucketName: "$[taskcat_autobucket]"

